apiVersion: app/v1
kind: Deployment
metadata:
  name: netflix app
  labels:
    app: netflix app
spec:
  replicas: 2
  selector:
    matchlabels:
      app: netflix app
  template:
    metadata:
      labels:
        app: netflix app
    spec:
      containers:
        - name: netflix-clone
          image: 078724664036.dkr.ecr.ap-south-1.amazonaws.com/netflix-cloneapp:296a8257d16140f2bc6e81c9ff1ba2ee04627d7f
          ports:
            - containerPort: 80
