apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabeLs:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
        - name: netflix-clone
          image: 078724664036.dkr.ecr.ap-south-1.amazonaws.com/netflix-cloneapp:fabaf1e2ca630e016ac3f96903520fa96835f09f
          ports:
            - containerPort: 80
