apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-clone
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: netflix.cloudiandevops.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netflix-clone
                port:
                  number: 80


