apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-clone
spec:
  ingressClassName: nginx
  rules:
  - http: netflix.cloudiandevops.com
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netflix-clone
            port:
              number: 80

